### PR TITLE
Implement mount_at for all platforms

### PR DESCRIPTION
**Pull request by fenhl**
Simply uses `mounts` and looks for the given path as a mount point in the result.

### CODE REVIEW

**Comment by myfreeweb** [comment]
This really should be the default implementation in the trait, like `uptime` and `boot_time` that are defined in terms of each other

https://github.com/myfreeweb/systemstat/blob/11230792edf4cda8fc12f17d304404710262ef0b/src/platform/common.rs#L35-L49

**Comment by myfreeweb** [comment]
Thanks!!

**Comment by fenhl** [comment]
Hey, any chance of getting a release with this?

**Comment by myfreeweb** [comment]
uploaded 0.1.5

**Pull request merged**
